name: CMake

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    env:
      BUILD_TYPE: Release
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false 
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies (ubuntu only)
      if: matrix.os == 'ubuntu-latest'
      run: |
            sudo apt-get update
            sudo apt-get install -y libgtk-3-dev

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
    
    - name: Upload .dll file (if any exists)
      if: ${{ runner.os == 'windows-latest' }}
      uses: actions/upload-artifact@v3
      with:
        name: sciter-pdf-${{ matrix.os }}.dll
        path: build/Release/*.dll
        retention-days: 1
    
    - name: Upload .so file (if any exists)
      if: ${{ runner.os == 'ubuntu-latest' }}
      uses: actions/upload-artifact@v3
      with:
        name: sciter-pdf-${{ matrix.os }}.so
        path: build/*.so
        retention-days: 1
    
    - name: Upload .dylib file (if any exists)
      if: ${{ runner.os == 'macos-latest' }}
      uses: actions/upload-artifact@v3
      with:
        name: sciter-pdf-${{ matrix.os }}.dylib
        path: build/*.dylib
        retention-days: 1
