name: CMake

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    env:
      BUILD_TYPE: Release
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: false 
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
    - uses: actions/checkout@v3
    
    - name: Install dependencies (ubuntu only)
      if: matrix.os == 'ubuntu-latest'
      run: |
            sudo apt-get update
            sudo apt-get install -y libgtk-3-dev

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
          
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          title: "sciter-pdf"
          files: |
            build/Release/sciter-pdf.dll
            build/libsciter-pdf.dylib
            build/libsciter-pdf.so
            
            
      
